disabled_rules:
  - line_length
  - trailing_whitespace
  - orphaned_doc_comment

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - comma_inheritance
  - comment_spacing
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_assert
  - discouraged_direct_init
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - indentation_width
  - is_disjoint
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nesting
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_literal_empty_collections
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_equatable
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - return_value_from_void_function
  - self_binding_parameter
  - shorthand_argument_default
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - trailing_closure
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - unownedself
  - untyped_error_in_catch
  - unused_control_flow_label
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

line_length:
  warning: 120
  error: 200

nesting:
  type_level: 2
  function_level: 3

file_header:
  required: false

private_outlet:
  allow_private_set: true

trailing_comma:
  mandatory_comma: false

type_contents_order:
  enabled: true
  order:
    - case
    - associated_type
    - type_alias
    - subtype
    - type_property
    - instance_property
    - weak_variable
    - deinitializer
    - subscript
    - initializer
    - type_method
    - view_lifecycles
    - instance_method
    - operator
    - subscript

force_unwrapping: warning
fatal_error_message: error
